module.exports = (ctx) => {
  with (ctx) {
    return [
      h('III. MÔ TẢ HỆ THỐNG XÂY DỰNG'),
      h2('3.1. Tên và phiên bản'),
      p(bold('Tên hệ thống: '), t('BookStore — Hệ thống bán sách trực tuyến')),
      p(bold('Phiên bản: '), t('1.0.0 (Development / Demo)')),
      p(bold('Ngôn ngữ giao diện: '), t('Tiếng Việt')),
      h2('3.2. Đối tượng sử dụng'),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          headerRow('Đối tượng', 'Mô tả', 'Hệ thống sử dụng'),
          dataRow('Khách vãng lai', 'Chưa đăng nhập, muốn duyệt và mua sách', 'Storefront (cổng 3000)'),
          dataRow('Khách hàng đã đăng ký', 'Có tài khoản, quản lý đơn hàng, ví điện tử, ngân hàng liên kết, wishlist, đánh giá, đổi trả', 'Storefront (cổng 3000)'),
          dataRow('Admin / Nhân viên', 'Quản lý sản phẩm, danh mục, đơn hàng, giao hàng, đổi trả, ví điện tử và yêu cầu rút tiền', 'Admin Panel (cổng 3001)'),
          dataRow('Super Admin', 'Tất cả quyền admin + phân quyền người dùng, hoàn tiền/xóa dữ liệu quan trọng/cấu hình hệ thống', 'Admin Panel (cổng 3001)'),
        ],
      }),
      new Paragraph({ text: '' }),
      h2('3.3. Luồng hoạt động chính'),
      p(t('Khách hàng truy cập Storefront → duyệt sản phẩm → thêm vào giỏ → đặt hàng (điền địa chỉ + chọn thanh toán) → theo dõi trạng thái đơn hàng trong tài khoản. Admin tiếp nhận đơn trên Admin Panel → xử lý theo quy trình pending → confirmed → processing → shipped → delivered; trước khi chuyển shipped phải nhập đơn vị vận chuyển và mã vận đơn. Khi đang giao, khách có thể xem trang theo dõi đơn hàng và xác nhận đã nhận hàng. Với đơn đã giao, khách có thể gửi yêu cầu đổi trả/hoàn tiền để admin xử lý.')),
      pageBreak(),

      // ════════════════════════════ CHƯƠNG IV ════════════════════════════
      h('IV. KIẾN TRÚC HỆ THỐNG'),
      h2('4.1. Mô hình kiến trúc tổng thể'),
      p(t('Hệ thống theo kiến trúc '), bold('SPA + REST API + AI service'), t(' (Single Page Application kết hợp PHP REST API cho nghiệp vụ chính và Python Django service cho phân tích/gợi ý):')),
      new Paragraph({
        children: [new TextRun({ text: '┌─────────────────────────┐      ┌─────────────────────────┐', font: 'Courier New', size: 20, color: '333333' })],
        spacing: { before: 60, after: 0 },
      }),
      new Paragraph({ children: [new TextRun({ text: '│  Frontend (React SPA)   │      │  Admin Panel (React SPA)│', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '│  Vite · Tailwind CSS    │      │  Vite · Tailwind CSS    │', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '│  cổng :3000             │      │  cổng :3001             │', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '└────────────┬────────────┘      └────────────┬────────────┘', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '             │  HTTP/JSON (REST API)            │', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '             └──────────────┬──────────────────┘', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '                            ▼', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              ┌─────────────────────────┐', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              │  Backend PHP (API Server)│', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              │  PHP 8+ · PDO · Router   │', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              │  cổng :5000             │', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              └─────────────┬───────────┘', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '                            │  PDO', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '                            ▼', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              ┌─────────────────────────┐', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              │  MySQL 8.0 Database      │', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              │  bookstore (15 bảng)     │', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ children: [new TextRun({ text: '              └─────────────────────────┘', font: 'Courier New', size: 20, color: '333333' })], spacing: { before: 0, after: 0 } }),
      new Paragraph({ text: '' }),
      h2('4.2. Công nghệ sử dụng'),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          headerRow('Thành phần', 'Công nghệ / Thư viện', 'Vai trò'),
          dataRow('Frontend (Storefront)', 'React 18, Vite, Tailwind CSS, TanStack Query v5', 'Giao diện khách hàng'),
          dataRow('Admin Panel', 'React 18, Vite, Tailwind CSS, Recharts, React Hook Form', 'Trang quản trị'),
          dataRow('Backend API', 'PHP 8+, PHP built-in server, PDO, JSON', 'REST API server'),
          dataRow('AI / Analytics service', 'Python Django, Django REST-style JsonResponse', 'Gợi ý sách, FAQ, phân tích doanh thu và top sản phẩm bán chạy'),
          dataRow('Database', 'MySQL 8.0, utf8mb4', 'Lưu trữ dữ liệu'),
          dataRow('Authentication', 'JWT (Access + Refresh Token), Google OAuth 2.0', 'Xác thực người dùng'),
          dataRow('Routing', 'React Router v6 (SPA routing)', 'Điều hướng phía client'),
          dataRow('State & Cache', 'TanStack Query (server state), React Context (cart/auth)', 'Quản lý trạng thái'),
          dataRow('Thông báo', 'React Hot Toast', 'Toast notification'),
          dataRow('Upload ảnh', 'Lưu ảnh cục bộ theo danh mục tại admin-panel/public và frontend/public', 'Dùng chung nguồn ảnh bìa giữa admin và storefront'),
        ],
      }),
      new Paragraph({ text: '' }),
      h2('4.3. Cấu trúc thư mục dự án'),
      p(t('Dự án được tổ chức thành các thư mục độc lập:')),
      bullet('book-store-main/frontend/     — Storefront React app'),
      bullet2('src/pages/   — các trang (Home, Product, Cart, Checkout, Profile…)'),
      bullet2('src/services/— wrapper gọi API (axios)'),
      bullet2('src/contexts/— CartContext, AuthContext'),
      bullet('book-store-main/admin-panel/  — Admin Panel React app'),
      bullet2('src/pages/   — Dashboard, Products, Orders, Users, Coupons, Settings…'),
      bullet('book-store-main/backend/      — PHP API'),
      bullet2('src/api/routes/ — orders.php, admin.php, auth.php, products.php…'),
      bullet2('src/middleware/ — AuthMiddleware, CorsMiddleware'),
      bullet('book-store-main/book-store-python/ — Python Django AI/analytics service'),
      bullet2('api/recommendation_engine.py — gợi ý sách cho người dùng'),
      bullet2('api/analytics_engine.py — phân tích doanh thu và top sản phẩm bán chạy'),
      bullet2('api/support_engine.py — dữ liệu FAQ động cho người dùng'),
      bullet('book-store-main/database/     — schema_mysql.sql'),
      pageBreak(),

      // ════════════════════════════ CHƯƠNG V ════════════════════════════
      h('V. THIẾT KẾ CƠ SỞ DỮ LIỆU'),
      h2('5.1. Danh sách bảng'),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          headerRow('STT', 'Tên bảng', 'Mô tả chức năng', 'Số cột chính'),
          dataRow('1', 'users', 'Tài khoản người dùng (customer, admin, super_admin)', '14'),
          dataRow('2', 'user_addresses', 'Địa chỉ giao hàng của người dùng', '10'),
          dataRow('3', 'categories', 'Danh mục sách (hỗ trợ phân cấp parent_id)', '10'),
          dataRow('4', 'authors', 'Thông tin tác giả', '6'),
          dataRow('5', 'publishers', 'Thông tin nhà xuất bản', '6'),
          dataRow('6', 'products', 'Sản phẩm sách (đầy đủ thông tin)', '32'),
          dataRow('7', 'product_images', 'Ảnh phụ của sản phẩm', '6'),
          dataRow('8', 'product_tags', 'Tag/từ khoá cho sản phẩm', '2'),
          dataRow('9', 'cart_items', 'Giỏ hàng (user_id hoặc session_id)', '6'),
          dataRow('10', 'wishlist', 'Danh sách yêu thích', '4'),
          dataRow('11', 'coupons', 'Mã giảm giá', '13'),
          dataRow('12', 'coupon_usage', 'Lịch sử sử dụng mã giảm giá', '5'),
          dataRow('13', 'orders', 'Đơn hàng, vận chuyển và thanh toán', '30+'),
          dataRow('14', 'order_items', 'Chi tiết sản phẩm trong đơn hàng', '8'),
          dataRow('15', 'payments', 'Giao dịch thanh toán', '12'),
          dataRow('16', 'reviews', 'Đánh giá sản phẩm', '12'),
          dataRow('17', 'settings', 'Cài đặt hệ thống (key-value)', '3'),
          dataRow('18', 'sliders', 'Banner/Slider trang chủ', '8'),
          dataRow('19', 'contact_messages', 'Tin nhắn liên hệ từ khách hàng', '7'),
          dataRow('20', 'return_requests', 'Yêu cầu đổi trả / hoàn tiền của khách hàng', '12'),
          dataRow('21', 'wallets', 'Ví điện tử nội bộ của người dùng', '5'),
          dataRow('22', 'user_bank_accounts', 'Tài khoản ngân hàng liên kết', '8'),
          dataRow('23', 'wallet_transactions', 'Lịch sử nạp, rút, hoàn tiền, thanh toán ví', '13'),
        ],
      }),
      new Paragraph({ text: '' }),
      h2('5.2. Quan hệ giữa các bảng chính'),
      p(t('Bảng ')), // will describe FK relationships
      bullet('users (1) ←→ (N) orders: một người dùng có nhiều đơn hàng (ON DELETE SET NULL để giữ lịch sử khi xóa user).'),
      bullet('orders (1) ←→ (N) order_items: một đơn hàng gồm nhiều dòng sản phẩm (ON DELETE CASCADE).'),
      bullet('products (1) ←→ (N) order_items: sản phẩm bị xóa không xóa dữ liệu đơn hàng (ON DELETE SET NULL).'),
      bullet('products (1) ←→ (N) product_images, product_tags: cascade xóa khi xóa sản phẩm.'),
      bullet('categories hỗ trợ self-reference (parent_id) để tổ chức phân cấp danh mục.'),
      bullet('coupons (1) ←→ (N) coupon_usage: theo dõi tần suất sử dụng mã theo từng user.'),
      bullet('orders (1) ←→ (N) return_requests: một đơn đã giao có thể phát sinh yêu cầu đổi trả hoặc hoàn tiền.'),
      bullet('users (1) ←→ (1) wallets và users (1) ←→ (N) wallet_transactions: quản lý số dư và lịch sử biến động ví.'),
      bullet('users (1) ←→ (N) user_bank_accounts: người dùng phải liên kết ngân hàng trước khi nạp/rút hoặc thanh toán qua ngân hàng/thẻ.'),
      h2('5.3. Các trường quan trọng trong bảng orders'),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          headerRow('Trường', 'Kiểu dữ liệu', 'Ý nghĩa'),
          dataRow('order_number', 'VARCHAR(20) UNIQUE', 'Mã đơn hàng hiển thị cho khách (vd: ORD-20240515-001)'),
          dataRow('status', "ENUM('pending','confirmed','processing','shipped','delivered','cancelled','refunded')", 'Trạng thái xử lý đơn hàng'),
          dataRow('payment_status', "ENUM('pending','paid','failed','refunded')", 'Trạng thái thanh toán'),
          dataRow('payment_method', "ENUM('cod','bank_transfer','card','wallet')", 'Phương thức thanh toán'),
          dataRow('subtotal / shipping_cost / discount_amount / total_amount', 'DECIMAL(12,0)', 'Các thành phần giá trị đơn hàng'),
          dataRow('shipping_provider', 'VARCHAR(50)', 'Đơn vị vận chuyển do admin nhập trước khi giao hàng'),
          dataRow('tracking_code', 'VARCHAR(100)', 'Mã vận đơn giao hàng'),
          dataRow('shipped_at / delivered_at', 'TIMESTAMP', 'Thời điểm chuyển sang đang giao và đã giao'),
          dataRow('coupon_id + coupon_code', 'INT + VARCHAR', 'Mã giảm giá đã áp dụng (lưu snapshot code)'),
        ],
      }),
      new Paragraph({ text: '' }),
      h2('5.4. Các bảng nghiệp vụ mới'),
      bullet('return_requests lưu loại yêu cầu (return/exchange), lý do, ghi chú khách, trạng thái xử lý, ghi chú admin và người xử lý.'),
      bullet('wallets lưu số dư hiện tại của mỗi người dùng; hệ thống tự tạo ví khi người dùng truy cập chức năng ví.'),
      bullet('wallet_transactions lưu mọi biến động ví: nạp tiền, rút tiền, thanh toán đơn hàng, hoàn tiền do hủy đơn/đổi trả.'),
      bullet('user_bank_accounts lưu ngân hàng đã liên kết; người dùng chọn tài khoản ngân hàng cụ thể khi nạp, rút hoặc thanh toán qua ngân hàng/thẻ.'),
      new Paragraph({ text: '' }),
      pageBreak(),
    ]
  }
}
