module.exports = (ctx) => {
  with (ctx) {
    return [
      new Paragraph({ text: '' }),
      new Paragraph({ text: '' }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 200, after: 80 },
        children: [new TextRun({ text: 'TRƯỜNG ĐẠI HỌC', bold: true, size: 26, font: 'Times New Roman', color: '333333' })],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: 'KHOA CÔNG NGHỆ THÔNG TIN', bold: true, size: 26, font: 'Times New Roman', color: '333333' })],
        spacing: { after: 400 },
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: 'BÁO CÁO ĐỒ ÁN MÔN HỌC', bold: true, size: 40, font: 'Times New Roman', color: PRIMARY })],
        spacing: { after: 200 },
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: 'XÂY DỰNG HỆ THỐNG BÁN SÁCH TRỰC TUYẾN', bold: true, size: 34, font: 'Times New Roman', color: '1E3A5F' })],
        spacing: { after: 100 },
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: '(BookStore Full-Stack Web Application)', italics: true, size: 26, font: 'Times New Roman', color: '555555' })],
        spacing: { after: 600 },
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: 'Công nghệ sử dụng: PHP · MySQL · React.js · Tailwind CSS', size: 22, font: 'Times New Roman', color: '444444' })],
        spacing: { after: 800 },
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: 'Năm học: 2024 – 2025', size: 24, font: 'Times New Roman', color: '333333' })],
        spacing: { after: 0 },
      }),
      pageBreak(),

      // ════════════════════════════ MỤC LỤC ════════════════════════════
      h('MỤC LỤC'),
      ...[
        ['I.',   'GIỚI THIỆU TỔNG QUAN', '3'],
        ['II.',  'PHÂN TÍCH HỆ THỐNG TƯƠNG TỰ NGOÀI THỰC TẾ', '4'],
        ['III.', 'MÔ TẢ HỆ THỐNG XÂY DỰNG', '6'],
        ['IV.',  'KIẾN TRÚC HỆ THỐNG', '7'],
        ['V.',   'THIẾT KẾ CƠ SỞ DỮ LIỆU', '9'],
        ['VI.',  'PHÂN TÍCH CHỨC NĂNG HỆ THỐNG', '11'],
        ['VII.', 'ĐÁNH GIÁ VÀ HƯỚNG PHÁT TRIỂN', '18'],
        ['VIII.','KẾT LUẬN', '19'],
      ].map(([num, title, page]) =>
        new Paragraph({
          children: [
            new TextRun({ text: `${num}  ${title}`, font: 'Times New Roman', size: 24, bold: true }),
            new TextRun({ text: `\t${page}`, font: 'Times New Roman', size: 24, color: '888888' }),
          ],
          spacing: { before: 60, after: 60 },
          tabStops: [{ type: 'right', position: convertInchesToTwip(5.2) }],
        })
      ),
      pageBreak(),

      // ════════════════════════════ CHƯƠNG I ════════════════════════════
      h('I. GIỚI THIỆU TỔNG QUAN'),
      h2('1.1. Bối cảnh và lý do chọn đề tài'),
      p(t('Thương mại điện tử tại Việt Nam tăng trưởng mạnh mẽ trong những năm gần đây, đặc biệt sau đại dịch COVID-19. Theo báo cáo của Hiệp hội Thương mại điện tử Việt Nam (VECOM), doanh thu thương mại điện tử B2C năm 2023 đạt hơn 20 tỷ USD, tăng 25% so với năm 2022. Trong đó, lĩnh vực sách và văn hóa phẩm chứng kiến sự bùng nổ khi các độc giả chuyển dần từ mua sách tại cửa hàng truyền thống sang mua trực tuyến.')),
      p(t('Xu hướng này tạo ra nhu cầu cấp thiết về các nền tảng thương mại điện tử chuyên biệt cho sách — nơi người đọc có thể dễ dàng tìm kiếm, đánh giá, và mua sách từ mọi thiết bị. Dự án ')),
      p(bold('BookStore'), t(' được xây dựng nhằm đáp ứng nhu cầu đó, đồng thời là cơ hội để nhóm áp dụng tổng hợp các kiến thức lập trình web full-stack trong môi trường thực tế.')),
      h2('1.2. Mục tiêu dự án'),
      bullet('Xây dựng hệ thống bán sách trực tuyến hoàn chỉnh từ giao diện khách hàng đến trang quản trị.'),
      bullet('Áp dụng kiến trúc tách biệt Frontend – Backend (REST API) hiện đại.'),
      bullet('Thiết kế cơ sở dữ liệu quan hệ đầy đủ cho một hệ thống thương mại điện tử thực tế.'),
      bullet('Triển khai các tính năng cốt lõi: quản lý sản phẩm, đặt hàng, thanh toán, ví điện tử, mã giảm giá, đánh giá sản phẩm.'),
      bullet('Xây dựng trang quản trị cho admin theo dõi đơn hàng, giao hàng, đổi trả, ví điện tử, doanh thu và quản lý nội dung.'),
      h2('1.3. Phạm vi dự án'),
      p(t('Hệ thống bao gồm 3 thành phần độc lập:')),
      bullet('Frontend (Storefront): Giao diện dành cho khách hàng tại cổng 3000.'),
      bullet('Admin Panel: Trang quản trị dành cho nhân viên/admin tại cổng 3001.'),
      bullet('Backend API: REST API PHP thuần tại cổng 5000, phục vụ cả hai giao diện trên.'),
      pageBreak(),

      // ════════════════════════════ CHƯƠNG II ════════════════════════════
      h('II. PHÂN TÍCH HỆ THỐNG TƯƠNG TỰ NGOÀI THỰC TẾ'),
      h2('2.1. Tổng quan các hệ thống tham khảo'),
      p(t('Nhóm đã nghiên cứu và tham khảo ba hệ thống bán sách/TMĐT lớn tại Việt Nam: Tiki, Fahasa Online và Shopee (phân khúc sách). Từ đó rút ra những tính năng thiết yếu và áp dụng vào thiết kế hệ thống của mình.')),
      h2('2.2. Phân tích chi tiết từng hệ thống'),
      h3('2.2.1. Tiki (tiki.vn)'),
      p(bold('Mô tả: '), t('Tiki là sàn TMĐT đa ngành hàng, trong đó sách là một trong những ngành hàng chiến lược. Tiki Books cung cấp hàng triệu đầu sách với kho hàng riêng (TikiNOW – giao hàng trong 2 giờ).')),
      p(bold('Điểm mạnh nổi bật:')),
      bullet('Tìm kiếm nâng cao với bộ lọc đa chiều: thể loại, nhà xuất bản, tác giả, giá, định dạng, ngôn ngữ.'),
      bullet('Hệ thống đánh giá và review sản phẩm có xác thực mua hàng.'),
      bullet('Quản lý đơn hàng thời gian thực với tracking vận chuyển.'),
      bullet('Hệ thống voucher, flash sale, và TikiXu (điểm thưởng).'),
      bullet('Hỗ trợ nhiều phương thức thanh toán: COD, thẻ, ví điện tử VNPay, Momo, ZaloPay.'),
      p(bold('Hạn chế: '), t('Giao diện phức tạp, nhiều quảng cáo, trải nghiệm mobile đôi khi chậm với kết nối yếu.')),
      h3('2.2.2. Fahasa Online (fahasa.com)'),
      p(bold('Mô tả: '), t('Fahasa là chuỗi nhà sách lớn nhất Việt Nam với hệ thống cửa hàng vật lý và website TMĐT tích hợp. Ưu điểm là danh mục sách phong phú, đặc biệt là sách giáo khoa, sách thiếu nhi và sách tiếng Việt.')),
      p(bold('Điểm mạnh nổi bật:')),
      bullet('Danh mục sách có cấu trúc phân cấp rõ ràng (thể loại → chủ đề → tác giả).'),
      bullet('Tích hợp giỏ hàng lưu trữ lâu dài, hỗ trợ khách vãng lai.'),
      bullet('Hệ thống thành viên với thẻ tích điểm Fahasa Card.'),
      bullet('Trang chi tiết sản phẩm đầy đủ: ISBN, NXB, năm xuất bản, tóm tắt, mục lục.'),
      p(bold('Hạn chế: '), t('Giao diện thiết kế cũ, thiếu tính năng so sánh sản phẩm, chức năng tìm kiếm chưa mạnh.')),
      h3('2.2.3. Shopee (shopee.vn — phân khúc Sách & Văn phòng phẩm)'),
      p(bold('Mô tả: '), t('Shopee là sàn marketplace lớn nhất Đông Nam Á. Tuy không chuyên sách, nhưng danh mục Sách & VPP của Shopee rất lớn với nhiều người bán cạnh tranh về giá.')),
      p(bold('Điểm mạnh nổi bật:')),
      bullet('UI/UX thân thiện, tối ưu cho mobile-first.'),
      bullet('Voucher miễn phí vận chuyển và flash sale hấp dẫn.'),
      bullet('Hệ thống chat trực tiếp với người bán.'),
      bullet('Đánh giá người mua kèm ảnh thực tế.'),
      p(bold('Hạn chế: '), t('Không có trang sản phẩm chuyên sâu (thiếu ISBN, thông tin tác giả đầy đủ), chất lượng hàng giả khó kiểm soát.')),
      h2('2.3. Bảng so sánh tính năng'),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          headerRow('Tính năng', 'Tiki', 'Fahasa', 'Shopee', 'BookStore (của nhóm)'),
          dataRow('Tìm kiếm nâng cao', '✅ Đầy đủ', '⚠️ Cơ bản', '⚠️ Cơ bản', '✅ Có (tìm kiếm + bộ lọc)'),
          dataRow('Giỏ hàng khách', '✅', '✅', '✅', '✅ Có (session)'),
          dataRow('Mã giảm giá', '✅', '✅', '✅', '✅ Có (coupon system)'),
          dataRow('Đánh giá sản phẩm', '✅ Có verify', '✅', '✅ Có ảnh', '✅ Có (chờ duyệt)'),
          dataRow('Wishlist', '✅', '✅', '✅', '✅ Có'),
          dataRow('Theo dõi đơn hàng', '✅ Thời gian thực', '✅', '✅', '✅ Có timeline theo trạng thái'),
          dataRow('Đăng nhập Google', '✅', '❌', '❌', '✅ Có'),
          dataRow('Admin dashboard', 'Riêng biệt', 'Riêng biệt', 'Seller Center', '✅ Tích hợp'),
          dataRow('Thanh toán online', '✅ Đa dạng', '✅', '✅', '⚠️ COD + chuyển khoản/thẻ thủ công + ví nội bộ'),
          dataRow('Quản lý kho hàng', '✅ Tự động', '✅', '✅ Seller', '✅ Thủ công'),
        ],
      }),
      new Paragraph({ text: '' }),
      p(italic('Ghi chú: ✅ = Hoàn thành đầy đủ · ⚠️ = Có nhưng hạn chế · ❌ = Không có')),
      h2('2.4. Rút ra yêu cầu cho hệ thống của nhóm'),
      p(t('Từ phân tích trên, nhóm xác định các yêu cầu ưu tiên cao cho BookStore:')),
      bullet('Trang chi tiết sản phẩm đầy đủ thông tin: ISBN, NXB, tác giả, năm xuất bản, số trang, ngôn ngữ.'),
      bullet('Giỏ hàng hỗ trợ cả khách vãng lai (session-based) lẫn khách đã đăng nhập.'),
      bullet('Hệ thống mã giảm giá linh hoạt (phần trăm / số tiền cố định, có hạn sử dụng và giới hạn người dùng).'),
      bullet('Luồng đơn hàng tách rõ trạng thái xử lý đơn và trạng thái thanh toán; không cho admin chuyển ngược trạng thái sai quy trình.'),
      bullet('Có nghiệp vụ giao hàng, mã vận đơn, khách xác nhận đã nhận hàng và theo dõi timeline vận chuyển.'),
      bullet('Có nghiệp vụ đổi trả/hoàn tiền sau khi đơn đã giao, liên kết với trạng thái xử lý ở admin.'),
      bullet('Có ví điện tử nội bộ, tài khoản ngân hàng liên kết, nạp/rút tiền và dùng ví để thanh toán.'),
      bullet('Admin panel thống kê doanh thu, quản lý đơn hàng, đổi trả, ví điện tử và thông báo vận hành.'),
      bullet('Hỗ trợ đăng nhập Google để giảm rào cản cho người dùng mới.'),
      pageBreak(),
    ]
  }
}
