module.exports = (ctx) => {
  with (ctx) {
    return [
      h('VI. PHÂN TÍCH CHỨC NĂNG HỆ THỐNG'),
      p(t('Phần này trình bày chi tiết từng nhóm chức năng, gồm mô tả luồng hoạt động, đánh giá mức độ hoàn thành và các trường hợp giới hạn.')),

      h2('6.1. Nhóm chức năng: Xác thực người dùng (Authentication)'),
      h3('6.1.1. Đăng ký tài khoản'),
      p(bold('Luồng hoạt động: '), t('Người dùng điền email + mật khẩu → Backend hash mật khẩu bằng bcrypt (cost 10) → Lưu vào bảng users với role="customer" → Trả về JWT access token + refresh token.')),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Đăng ký với email hợp lệ chưa tồn tại → tạo tài khoản thành công.'),
      bullet('Mật khẩu được hash an toàn bằng bcrypt, không lưu plaintext.'),
      bullet('Trả về JWT để người dùng đăng nhập ngay sau khi đăng ký.'),
      p(bold('Tình huống CHƯA HOÀN THÀNH / HẠN CHẾ:')),
      bullet('Chưa có xác minh email (email_verified = 0 mặc định, không gửi email xác nhận).'),
      bullet('Chưa có kiểm tra độ mạnh mật khẩu phía backend.'),
      bullet('Không có captcha chống đăng ký tự động.'),

      h3('6.1.2. Đăng nhập email/mật khẩu'),
      p(bold('Luồng: '), t('Frontend gửi email + password → Backend tra bảng users, so sánh bcrypt → Tạo JWT access token (exp: 15 phút) + refresh token (exp: 7 ngày) → Lưu refresh token vào cookie httpOnly hoặc localStorage.')),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Đăng nhập đúng email/mật khẩu → nhận token, điều hướng về trang chủ.'),
      bullet('Sai mật khẩu → trả lỗi 401 rõ ràng.'),
      bullet('Access token refresh tự động khi hết hạn.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Chưa có giới hạn số lần đăng nhập sai (brute-force protection).'),
      bullet('Chưa hỗ trợ đăng xuất từ xa (revoke token trên server).'),

      h3('6.1.3. Đăng nhập Google OAuth'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Người dùng nhấn "Đăng nhập Google" → Google Identity Services trả về credential → frontend gửi credential cho backend → backend xác minh với GOOGLE_CLIENT_ID → tạo/cập nhật tài khoản và trả về JWT.'),
      bullet('Nếu email Google đã tồn tại → liên kết tài khoản, không tạo trùng.'),
      bullet('Sau khi load lại trang, AuthContext gọi lại /auth/me để khôi phục phiên đăng nhập nếu token còn hợp lệ.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Cần cấu hình GOOGLE_CLIENT_ID trong .env và Authorized JavaScript origins đúng domain/port — không hoạt động nếu thiếu.'),
      bullet('Chưa xử lý trường hợp Google thu hồi quyền.'),

      h2('6.2. Nhóm chức năng: Sản phẩm (Products)'),
      h3('6.2.1. Xem danh sách và tìm kiếm sản phẩm'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Xem danh sách sản phẩm có phân trang (page, limit).'),
      bullet('Lọc theo danh mục (category_id hoặc slug).'),
      bullet('Tìm kiếm full-text theo tiêu đề (LIKE %keyword%).'),
      bullet('Sắp xếp theo: newest, price_asc, price_desc, bestseller, rating.'),
      bullet('Lọc kết hợp: danh mục + giá + tác giả + NXB + ngôn ngữ.'),
      bullet('Trang chi tiết sản phẩm: đầy đủ ISBN, NXB, tác giả, số trang, năm xuất bản, ngôn ngữ, dịch giả.'),
      bullet('Hiển thị đánh giá trung bình và số lượt đánh giá.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Tìm kiếm LIKE không tối ưu khi dataset lớn (không có full-text index MySQL hay Elasticsearch).'),
      bullet('Không có gợi ý tìm kiếm (autocomplete).'),
      bullet('Có khối gợi ý sách cá nhân hóa bằng Python AI service; sản phẩm liên quan ở trang chi tiết vẫn chủ yếu dựa theo danh mục.'),

      h3('6.2.2. Quản lý sản phẩm (Admin)'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Thêm/sửa/xóa sản phẩm với đầy đủ các trường.'),
      bullet('Upload ảnh bìa sản phẩm theo danh mục; ảnh được lưu đồng bộ ở admin-panel/public/images/covers/{ten-danh-muc}/ và frontend/public/images/covers/{ten-danh-muc}/.'),
      bullet('Khi thêm danh mục mới, hệ thống tự tạo thư mục ảnh bìa tương ứng để admin chọn và lưu ảnh đúng nơi.'),
      bullet('Upload nhiều ảnh sản phẩm (primary + gallery).'),
      bullet('Thêm/xóa tag sản phẩm.'),
      bullet('Bật/tắt hiển thị sản phẩm (is_active).'),
      bullet('Admin bật/tắt "Đang bán" (is_active) và chọn "Sách nổi bật" (is_featured).'),
      bullet('Nhãn "Sách bán chạy" không cho admin tick thủ công; hệ thống tự xác định theo sales_count và sắp xếp theo doanh số.'),
      bullet('Quản lý tồn kho (stock), giá gốc, giá khuyến mãi, % giảm giá.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Chưa có import hàng loạt từ Excel/CSV.'),
      bullet('Không có lịch sử thay đổi giá (price history).'),
      bullet('Tồn kho không tự động trừ khi đặt hàng (cần thêm logic stock reservation).'),

      h2('6.3. Nhóm chức năng: Giỏ hàng (Cart)'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Thêm sản phẩm vào giỏ khi chưa đăng nhập (session-based, lưu bằng session_id cookie).'),
      bullet('Thêm sản phẩm vào giỏ khi đã đăng nhập (user_id).'),
      bullet('Cập nhật số lượng, xóa từng sản phẩm, xóa toàn bộ giỏ.'),
      bullet('Hiển thị tổng tiền tự động cập nhật.'),
      bullet('Chuyển giỏ hàng session sang user khi đăng nhập (cart merge).'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Không kiểm tra tồn kho khi thêm vào giỏ — có thể thêm số lượng vượt stock.'),
      bullet('Giỏ hàng session bị mất khi hết phiên trình duyệt.'),
      bullet('Không có giới hạn số lượng tối đa trong giỏ.'),

      h2('6.4. Nhóm chức năng: Đặt hàng và Thanh toán (Checkout)'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Điền địa chỉ giao hàng đầy đủ (tên, điện thoại, tỉnh/thành, quận/huyện, địa chỉ chi tiết).'),
      bullet('Chọn phương thức thanh toán: COD, chuyển khoản ngân hàng, thẻ tín dụng/thẻ ngân hàng, ví điện tử BookStore.'),
      bullet('Người dùng phải liên kết tài khoản ngân hàng trước khi nạp/rút ví hoặc dùng phương thức chuyển khoản/thẻ.'),
      bullet('Thanh toán bằng ví kiểm tra số dư trước khi tạo đơn; nếu đủ tiền thì trừ ví và đặt payment_status = paid.'),
      bullet('Áp dụng mã giảm giá (validate phía backend: trạng thái bật/tắt, hạn dùng, min_purchase, usage_limit, per_user_limit).'),
      bullet('Tính phí vận chuyển tự động dựa trên tỉnh/thành.'),
      bullet('Tạo đơn hàng với order_number duy nhất.'),
      bullet('Trừ used_count của coupon sau khi đặt hàng thành công.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Chuyển khoản và thẻ đang là nghiệp vụ mô phỏng/thủ công, admin xác nhận thanh toán trong hệ thống; chưa tích hợp cổng VNPay/MoMo/Stripe thật.'),
      bullet('Không có xác nhận email tự động sau khi đặt hàng.'),
      bullet('Không tự động trừ stock sau khi đặt — cần xử lý thủ công hoặc thêm trigger.'),
      bullet('Chưa có đối soát tự động với ngân hàng ngoài hệ thống.'),

      h2('6.5. Nhóm chức năng: Quản lý đơn hàng'),
      h3('6.5.1. Phía khách hàng'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Xem danh sách đơn hàng cá nhân với đầy đủ thông tin.'),
      bullet('Xem chi tiết đơn hàng: sản phẩm, giá, phí ship, giảm giá, đơn vị vận chuyển, mã vận đơn.'),
      bullet('Theo dõi đơn hàng bằng timeline khi đơn đang giao hoặc đã giao.'),
      bullet('Xác nhận "Đã nhận hàng" khi đơn ở trạng thái shipped; sau đó đơn chuyển sang delivered và COD được cập nhật payment_status = paid.'),
      bullet('Hủy đơn hàng khi còn hợp lệ: pending hoặc confirmed.'),
      bullet('Gửi yêu cầu đổi trả/hoàn tiền sau khi đơn đã giao.'),
      bullet('Hiển thị badge trạng thái với màu sắc trực quan.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Không có thông báo real-time khi trạng thái đơn thay đổi.'),
      bullet('Tracking vận chuyển là timeline nội bộ theo dữ liệu admin nhập, chưa lấy dữ liệu trực tiếp từ GHN/GHTK/Viettel Post.'),
      h3('6.5.2. Phía Admin'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Xem toàn bộ đơn hàng với bộ lọc: trạng thái đơn, trạng thái thanh toán, trạng thái đổi trả, khoảng ngày.'),
      bullet('Tìm kiếm đơn hàng theo order_number, tên khách, email, số điện thoại hoặc mã vận đơn.'),
      bullet('Cập nhật trạng thái đúng quy trình: pending → confirmed → processing → shipped → delivered; không cho chọn ngược trạng thái.'),
      bullet('Trước khi chuyển sang shipped bắt buộc nhập đơn vị vận chuyển và tracking_code; nhập thông tin vận chuyển xong thì đơn chuyển sang đang giao.'),
      bullet('Admin được xử lý đổi trả/hoàn tiền trong phạm vi nghiệp vụ; super_admin có thêm quyền xử lý dữ liệu nhạy cảm và quyền cao nhất.'),
      bullet('Xem chi tiết đơn: sản phẩm, địa chỉ giao hàng, ghi chú khách hàng.'),
      bullet('Thông báo admin hiển thị các đơn mới, yêu cầu đổi trả và yêu cầu rút tiền ví cần xử lý.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Không có in phiếu giao hàng (packing slip).'),
      bullet('Không có tích hợp API vận chuyển (GHTK, GHN, ViettelPost).'),

      h2('6.6. Nhóm chức năng: Mã giảm giá (Coupons)'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Tạo coupon kiểu phần trăm (percentage) hoặc số tiền cố định (fixed).'),
      bullet('Thiết lập: giá trị, giảm tối đa (max_discount), đơn tối thiểu (min_purchase).'),
      bullet('Giới hạn tổng lượt dùng (usage_limit) và lượt dùng mỗi người (per_user_limit).'),
      bullet('Thời hạn hiệu lực (start_date, end_date).'),
      bullet('Validate tất cả điều kiện phía backend trước khi áp dụng.'),
      bullet('Lưu lịch sử sử dụng vào bảng coupon_usage.'),
      bullet('Admin có thể bật/tắt voucher; khi hết hạn hoặc đạt usage_limit hệ thống hiển thị trạng thái hiệu lực là hết hạn/hết lượt.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Không có coupon theo danh mục hoặc theo sản phẩm cụ thể.'),
      bullet('Không thể áp nhiều coupon đồng thời cho một đơn hàng.'),

      h2('6.7. Nhóm chức năng: Đánh giá sản phẩm (Reviews)'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Khách đã đăng nhập gửi đánh giá: rating (1-5 sao), tiêu đề, nội dung, ưu điểm, nhược điểm.'),
      bullet('Đánh giá chờ duyệt (is_approved = 0) trước khi hiển thị công khai.'),
      bullet('Admin duyệt/ẩn đánh giá.'),
      bullet('Cập nhật rating_avg và rating_count trên sản phẩm.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Chưa kiểm tra is_verified_purchase — người dùng có thể đánh giá sản phẩm chưa mua.'),
      bullet('Không có cơ chế báo cáo (report) đánh giá vi phạm.'),

      h2('6.8. Nhóm chức năng: Dashboard và Thống kê (Admin)'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Tổng quan: tổng đơn hàng, doanh thu, số khách hàng, tổng sản phẩm, đơn chờ xử lý và sách sắp hết hàng.'),
      bullet('Biểu đồ doanh thu dùng dữ liệu PHP và có thể ưu tiên dữ liệu phân tích từ Python AI service khi service đang chạy.'),
      bullet('Dashboard có biểu đồ tồn kho theo danh mục/tác giả, giá trị hàng tồn và bảng sản phẩm tồn kho.'),
      bullet('Python AI service cung cấp thống kê doanh thu 30 ngày và top sản phẩm bán chạy.'),
      bullet('Danh sách đơn hàng gần đây với badge trạng thái.'),
      bullet('Thống kê theo khoảng thời gian (7 ngày, 30 ngày, 12 tháng).'),
      bullet('Có khu vực thông báo vận hành: đơn mới, đổi trả cần xử lý, rút tiền ví đang chờ.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Chưa có phân tích hành vi người dùng nâng cao như funnel, bounce rate hoặc cohort.'),
      bullet('Cảnh báo tồn kho hiện ở mức thống kê trong dashboard, chưa có gửi email/SMS tự động.'),

      h2('6.8.1. Nhóm chức năng: Python AI service'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Gợi ý sách cho người dùng ở trang chủ thông qua endpoint /ai/recommendations/user/.'),
      bullet('Cung cấp FAQ động cho trang Câu hỏi thường gặp thông qua endpoint /ai/support/faq/; frontend có fallback nếu service Python chưa chạy.'),
      bullet('Phân tích doanh thu theo ngày qua endpoint /ai/analytics/overview/.'),
      bullet('Thống kê top sản phẩm bán chạy qua endpoint /ai/analytics/top-products/.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('AI hiện là service phân tích/gợi ý mức cơ bản dựa trên dữ liệu đơn hàng, sản phẩm và danh mục; chưa huấn luyện mô hình machine learning phức tạp.'),
      bullet('Cần chạy riêng Django service tại cổng 8000; nếu service chưa chạy thì frontend/admin dùng dữ liệu PHP hoặc fallback.'),

      h2('6.9. Nhóm chức năng: Đổi trả và hoàn tiền'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Khách hàng chỉ được gửi yêu cầu đổi trả khi đơn đã giao thành công.'),
      bullet('Yêu cầu gồm loại yêu cầu (đổi hàng hoặc trả hàng/hoàn tiền), lý do và ghi chú chi tiết.'),
      bullet('Backend chặn tạo trùng yêu cầu đang pending/approved/completed cho cùng một đơn.'),
      bullet('Admin xem danh sách yêu cầu đổi trả, duyệt/từ chối/hoàn tất và nhập ghi chú xử lý.'),
      bullet('Khi hoàn tiền, tiền được cộng vào ví điện tử của người dùng và ghi lịch sử wallet_transactions.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Chưa có upload ảnh/video bằng chứng đổi trả.'),
      bullet('Chưa có quy trình kho nhận lại hàng và kiểm tra chất lượng sản phẩm trả về.'),

      h2('6.10. Nhóm chức năng: Ví điện tử và ngân hàng liên kết'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Mỗi người dùng có ví điện tử riêng, hiển thị số dư trong trang Profile.'),
      bullet('Người dùng có thể thêm nhiều tài khoản ngân hàng liên kết và chọn một tài khoản cụ thể khi giao dịch.'),
      bullet('Nạp tiền vào ví tạo giao dịch credit; rút tiền tạo giao dịch debit chờ admin duyệt.'),
      bullet('Ví điện tử là một phương thức thanh toán; hệ thống kiểm tra số dư và trừ tiền ngay khi đặt hàng bằng ví.'),
      bullet('Khi hủy đơn hoặc hoàn trả phát sinh tiền thừa, hệ thống cộng tiền vào ví và lưu lịch sử giao dịch.'),
      bullet('Admin có màn quản lý ví điện tử: tìm kiếm giao dịch, xem số dư, ngân hàng liên kết, duyệt/từ chối yêu cầu rút tiền.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Nạp/rút ngân hàng là mô phỏng nghiệp vụ nội bộ, chưa kết nối API ngân hàng thật.'),
      bullet('Chưa có xác thực OTP cho giao dịch ví.'),

      h2('6.11. Nhóm chức năng: Wishlist'),
      p(bold('Tình huống HOÀN THÀNH:')),
      bullet('Thêm/xóa sản phẩm vào danh sách yêu thích.'),
      bullet('Xem danh sách yêu thích trong trang Profile.'),
      bullet('Chuyển từ wishlist sang giỏ hàng trực tiếp.'),
      p(bold('Tình huống HẠN CHẾ:')),
      bullet('Chỉ hoạt động với người dùng đã đăng nhập.'),
      bullet('Không có chia sẻ wishlist với người khác.'),

      h2('6.12. Tóm tắt chức năng theo mức độ hoàn thành'),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          headerRow('Nhóm chức năng', 'Mức hoàn thành', 'Ghi chú'),
          dataRow('Đăng ký / Đăng nhập', '✅ ~85%', 'Thiếu xác minh email, rate limiting'),
          dataRow('Google OAuth', '✅ ~80%', 'Cần cấu hình .env đúng'),
          dataRow('Duyệt & tìm kiếm sản phẩm', '✅ ~90%', 'Tìm kiếm LIKE đơn giản'),
          dataRow('Quản lý sản phẩm (Admin)', '✅ ~88%', 'Có upload ảnh bìa theo danh mục, thiếu import Excel'),
          dataRow('Giỏ hàng', '✅ ~85%', 'Không validate stock khi thêm vào'),
          dataRow('Đặt hàng / Checkout', '✅ ~86%', 'Có ví nội bộ, chưa tích hợp cổng thanh toán thật'),
          dataRow('Quản lý đơn hàng', '✅ ~92%', 'Có quy trình trạng thái và tracking nội bộ'),
          dataRow('Đổi trả / Hoàn tiền', '✅ ~82%', 'Có yêu cầu đổi trả và hoàn tiền vào ví'),
          dataRow('Ví điện tử', '✅ ~85%', 'Có nạp/rút/thanh toán ví, ngân hàng liên kết; chưa OTP/API ngân hàng'),
          dataRow('Mã giảm giá', '✅ ~90%', 'Không hỗ trợ multi-coupon'),
          dataRow('Đánh giá sản phẩm', '✅ ~75%', 'Chưa verify purchase'),
          dataRow('Dashboard & Thống kê', '✅ ~88%', 'Có doanh thu, tồn kho, biểu đồ Recharts và dữ liệu AI analytics khi Python service chạy'),
          dataRow('Python AI service', '✅ ~75%', 'Có gợi ý sách, FAQ, doanh thu 30 ngày và top sản phẩm; chưa có ML nâng cao'),
          dataRow('Wishlist', '✅ ~90%', 'Chỉ cho user đăng nhập'),
          dataRow('Quản lý người dùng', '✅ ~85%', 'CRUD đầy đủ, thiếu bulk actions'),
          dataRow('Cài đặt hệ thống', '⚠️ ~60%', 'UI cơ bản, chưa email config'),
          dataRow('Thanh toán online thực', '❌ 0%', 'Chưa có cổng thanh toán thật; hiện có COD, chuyển khoản/thẻ thủ công và ví nội bộ'),
          dataRow('Thông báo email tự động', '❌ 0%', 'Chưa tích hợp SMTP / mail service'),
        ],
      }),
      new Paragraph({ text: '' }),
      pageBreak(),
    ]
  }
}
